# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/TaskManager"
        mkdir "$GITHUB_WORKSPACE/artifacts/TaskProcessor"
    - name: Publish TaskManager
      run: dotnet publish TaskManager/TaskManager.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/TaskManager"
    - name: Publish TaskProcessor
      run: dotnet publish TaskProcessor/TaskProcessor.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/TaskProcessor"
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
      with:
        version: latest
    - name: Package TaskManager
      run: |
        octo pack --id="TaskManager" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/TaskManager" --outFolder="$GITHUB_WORKSPACE/artifacts"
    - name: Package TaskProcessor
      run: |
        octo pack --id="TaskProcessor" --format="Zip" --version="$PACKAGE_VERSION" --basePath="$GITHUB_WORKSPACE/artifacts/TaskProcessor" --outFolder="$GITHUB_WORKSPACE/artifacts"
      
    
